apiVersion: v1
kind: PersistentVolume
metadata:
  name: gndf-db-data
  labels:
    app: mongodb
    version: "3.2.10"
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: gndf-db-data
    fsType: ext4