apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: gndf
  name: db
  labels:
    app: mongodb
    version: "3.2.10"
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mongodb
        version: "3.2.10"
    spec:
      containers:
      - name: gndf-mongodb
        image: nebo15/alpine-mongodb:3.2.10
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 27017
          - containerPort: 28017
        env:
          - name: MAX_RAM
            value: "512Mb"
        volumeMounts:
        - mountPath: /data/db
          name: db-data
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
      volumes:
      - name: db-data
        persistentVolumeClaim:
          claimName: gndf-db-data-claim