apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: gndf
  name: gndf-db-data-claim
  labels:
    app: mongodb
    version: "3.2.10"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: standard