apiVersion: v1
kind: Service
metadata:
  namespace: gndf
  name: landing-svc
  labels:
    app: "landing"
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: "landing"
  type: ClusterIP
