apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: gndf
  name: api
  labels:
    app: "api"
    version: "1.1.7"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "api"
  template:
    metadata:
      labels:
        app: "api"
        version: "1.1.7"
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
            {
                "name": "gndf-api-init",
                "image": "edenlabllc/gandalf.api:1.1.7",
                "imagePullPolicy": "IfNotPresent",
                "command": ["/bin/sh", "-c"],
                "args": ["cp -r /app /tmp && chmod -R 777 /tmp/app"],
                "volumeMounts": [{
                  "name": "shared-app",
                  "mountPath": "/tmp/app"
                }]
            }
        ]'
    spec:
      containers:
      - name: gndf-api
        image: edenlabllc/gandalf.api:1.1.7
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9000
          protocol: TCP
        env:
        - name: APP_ENV
          value: "prod"
        - name: DB_CONNECTION
          value: "mongodb"
        - name: DB_HOST
          value: "db-svc"
        - name: DB_PORT
          value: "27017"
        - name: DB_DATABASE
          value: "gndf"
        - name: DB_USERNAME
          value: ""
        - name: DB_PASSWORD
          value: ""
        - name: APP_DEBUG
          value: "true"
        # Postmark
        - name: EMAIL_ENABLED
          value: "true"
        - name: POSTMARK_TOKEN
          value: "4b0de40a-3c17-4424-85d7-4cf0dc396a97"
        - name: POSTMARK_SENDER_EMAIL
          value: "support@gndf.io"
        - name: POSTMARK_TEMPLATE_WELCOME_ID
          value: "689382"
        - name: POSTMARK_TEMPLATE_RESET_PASSWORD_ID
          value: "689401"
        - name: POSTMARK_TEMPLATE_INVITE_ID
          value: "743701"
        # Links
        - name: LINK_DUMP_PROJECT
          value: "http://api-gndf.ehealth.world/dump"
        - name: LINK_CONFIRMATION_EMAIL
          value: "http://apps-gndf.ehealth.world/#/activate/{code}"
        - name: LINK_RESET_PASSWORD
          value: "http://apps-gndf.ehealth.world/#/reset/confirm?token={code}"
        - name: LINK_INVITE
          value: "http://apps-gndf.ehealth.world/#/sign-up"
        - name: LINK_ADMIN_VARIANT
          value: "743701"
        # Metrics
        - name: STATUS_DPM_LINK
          value: "http://status-gndf.ehealth.world/api/v1/metrics/1/points"
        - name: STATUS_ACCESS_TOKEN
          value: "8enNc604AI1JVL96Ll4v"
        - name: INTERCOM_ENABLED
          value: "false"
        - name: MIXPANEL_ENABLED
          value: "false"
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 2
            memory: 1Gi
        readinessProbe:
          tcpSocket:
            port: 9000
          failureThreshold: 6
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
      - name: gndf-nginx
        image: nginx:1.11.10-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/conf.d
        - name: shared-app
          mountPath: /app
      volumes:
        - name: nginx-config-volume
          configMap:
            name: nginx-api-gndf
        - name: shared-app
          emptyDir: {}